source "https://rubygems.org"

#gem "win32console", '1.3.0', :group => :test, :platforms=>[:mingw], :require => RUBY_PLATFORM.include?('mingw') && 'win32console'
gem 'minitest-reporters', '>= 0.14.0', :group => :test
gem "rack-test", :require => "rack/test", :group => :test
gem 'minitest', :group=>:test

#gem 'thin'
gem 'rack'
gem 'json'
gem 'pry', :group => :test
