source "https://rubygems.org"

#gem "win32console", '1.3.0', :group => :test, :platforms=>[:mingw], :require => RUBY_PLATFORM.include?('mingw') && 'win32console'
gem 'minitest-reporters', '>= 0.14.0', :group => :test
gem "rack-test", :require => "rack/test", :group => :test
gem 'minitest', :group=>:test

gem 'rake', "~>10.1.0"
#gem 'thin', "~>1.5.1"
gem 'rack', "~>1.5.2"
gem 'json'


