require 'rake/testtask'

desc "CITest_Ruby: run CHECK-IN tests"
Rake::TestTask.new(:citest) do |t|
        t.libs << 'components'
        t.libs << 'test'
        t.libs << '.'
        t.test_files = FileList["test/*_test.rb"]
end


task :server => [:citest] do
    exec("ruby", "-I.:components", "server.rb")
end

